dummy_dist: 50.0
dummy_dist_rate: 0.0
dummy_rel_vol: 0.0
dynamic_extrapolation_samples:
- 0.1
- 0.25
- 1
- 2
- 4
flatten_observation: true
lane_circ_sensor_range_radius: 50.0
lane_rect_sensor_range_length: 100.0
lane_rect_sensor_range_width: 7.0
lidar_elli_num_beams: 20
lidar_elli_sensor_range_semi_major_axis: 100.0
lidar_elli_sensor_range_semi_minor_axis: 100.0
max_lane_merge_range: 5000.0
non_strict_check_circle_radius: 0.3
observe_a_ego: true
observe_distance_goal_lat: true
observe_distance_goal_long: true
observe_distance_goal_long_lane: false
observe_distance_goal_orientation: true
observe_distance_goal_time: true
observe_distance_goal_velocity: false
observe_dynamic_extrapolated_positions: true
observe_global_turn_rate: false
observe_heading: false
observe_is_collision: true
observe_is_friction_violation: false
observe_is_goal_reached: true
observe_is_off_road: true
observe_is_time_out: true
observe_lane_circ_surrounding: true
observe_lane_rect_surrounding: false
observe_lat_offset: false
observe_left_marker_distance: false
observe_left_road_edge_distance: false
observe_lidar_elli_surrounding: false
observe_remaining_steps: true
observe_right_marker_distance: false
observe_right_road_edge_distance: false
observe_static_extrapolated_positions: false
observe_steering_angle: false
observe_v_ego: true
relax_is_goal_reached: true
render_combine_frames: false
render_dynamic_extrapolated_positions: true
render_ego_lanelet_center_vertices: false
render_global_ccosy: false
render_lane_circ_surrounding_area: true
render_lane_circ_surrounding_obstacles: true
render_lane_rect_surrounding_area: false
render_lane_rect_surrounding_obstacles: false
render_lidar_elli_surrounding_beams: false
render_lidar_elli_surrounding_obstacles: false
render_local_ccosy: false
render_road_boundaries: false
render_skip_timesteps: 1
render_static_extrapolated_positions: false
reward_collision: -20.0
reward_friction: 0.0
reward_friction_violation: -5.0
reward_get_close_coefficient: 0.5
reward_goal_distance_coefficient: 0.2
reward_goal_reached: 50.0
reward_obs_distance_coefficient: 0.1
reward_off_road: -10.0
reward_reverse_driving: 0.0
reward_stay_in_road_center: 0.0
reward_time_out: -10.0
reward_type: sparse_reward
static_extrapolation_samples:
- 1
- 2
- 5
- 10
- 25
strict_off_road_check: false
terminate_on_collision: true
terminate_on_friction_violation: false
terminate_on_goal_reached: true
terminate_on_off_road: true
terminate_on_time_out: true
vehicle_params:
  vehicle_model: 2
  vehicle_type: 2
